version: '3.9'

services:
  db:
    container_name: mongo_db
    image: mongo:4.2.22
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - star-wars-network
    restart: unless-stopped

  app:
    container_name: star-wars
    build: .
    ports:
      - "3080:3080"
    networks:
      - star-wars-network
    depends_on:
      - db

networks:
  star-wars-network:



